development:
  bucket: 
  access_key_id: 
  secret_access_key: 
  simple_db_consistent_reads: false

test:
  bucket: 
  access_key_id: 
  secret_access_key: 
  simple_db_consistent_reads: false

production:
  bucket: 
  access_key_id: 
  secret_access_key: 
  simple_db_consistent_reads: false